import type { Currency, LivePrice } from '@/lib/types';
import { RectangleEllipsis } from 'lucide-react';

export const currencies: Currency[] = [
  { code: 'IRT', name: 'تومان ایران' },
  { code: 'IRR', name: 'ریال ایران' },
  { code: 'USD', name: 'دلار آمریکا' },
  { code: 'EUR', name: 'یورو' },
  { code: 'GBP', name: 'پوند بریتانیا' },
  { code: 'JPY', name: 'ین ژاپن' },
  { code: 'AUD', name: 'دلار استرالیا' },
  { code: 'CAD', name: 'دلار کانادا' },
  { code: 'CHF', name: 'فرانک سوئیس' },
  { code: 'CNY', name: 'یوان چین' },
];

export const mockExchangeRates: { [key: string]: number } = {
  // Rates against USD
  'USD-IRR': 590000, 
  'USD-EUR': 0.93,
  'USD-JPY': 157.7,
  'USD-GBP': 0.79,
  'USD-AUD': 1.51,
  'USD-CAD': 1.37,
  'USD-CHF': 0.9,
  'USD-CNY': 7.25,
};

export const iranCities: { label: string; value: string }[] = [
    { label: 'تهران', value: 'Tehran' },
    { label: 'مشهد', value: 'Mashhad' },
    { label: 'اصفهان', value: 'Isfahan' },
    { label: 'کرج', value: 'Karaj' },
    { label: 'شیراز', value: 'Shiraz' },
    { label: 'تبریز', value: 'Tabriz' },
    { label: 'قم', value: 'Qom' },
    { label: 'اهواز', value: 'Ahvaz' },
    { label: 'کرمانشاه', value: 'Kermanshah' },
    { label: 'ارومیه', value: 'Urmia' },
    { label: 'رشت', value: 'Rasht' },
    { label: 'زاهدان', value: 'Zahedan' },
    { label: 'همدان', value: 'Hamadan' },
    { label: 'کرمان', value: 'Kerman' },
    { label: 'یزد', value: 'Yazd' },
    { label: 'اردبیل', value: 'Ardabil' },
    { label: 'بندرعباس', value: 'Bandar Abbas' },
    { label: 'اراک', value: 'Arak' },
    { label: 'اسلامشهر', value: 'Eslamshahr' },
    { label: 'زنجان', value: 'Zanjan' },
    { label: 'سنندج', value: 'Sanandaj' },
    { label: 'قزوین', value: 'Qazvin' },
    { label: 'خرم‌آباد', value: 'Khorramabad' },
    { label: 'گرگان', value: 'Gorgan' },
    { label: 'ساری', value: 'Sari' },
];

export const unitCategories: { [key: string]: string[] } = {
  length: ['meter', 'kilometer', 'centimeter', 'millimeter', 'mile', 'yard', 'foot', 'inch'],
  mass: ['kilogram', 'gram', 'milligram', 'pound', 'ounce'],
  temperature: ['celsius', 'fahrenheit', 'kelvin'],
  volume: ['liter', 'milliliter', 'cubic-meter', 'gallon', 'quart', 'pint', 'cup'],
};

export const unitNames = {
    'طول': {
        meter: 'متر (meter)',
        kilometer: 'کیلومتر (kilometer)',
        centimeter: 'سانتی‌متر (centimeter)',
        millimeter: 'میلی‌متر (millimeter)',
        mile: 'مایل (mile)',
        yard: 'یارد (yard)',
        foot: 'فوت (foot)',
        inch: 'اینچ (inch)',
    },
    'جرم': {
        kilogram: 'کیلوگرم (kilogram)',
        gram: 'گرم (gram)',
        milligram: 'میلی‌گرم (milligram)',
        pound: 'پوند (pound)',
        ounce: 'اونس (ounce)',
    },
    'دما': {
        celsius: 'سلسیوس (celsius)',
        fahrenheit: 'فارنهایت (fahrenheit)',
        kelvin: 'کلوین (kelvin)',
    },
    'حجم': {
        liter: 'لیتر (liter)',
        milliliter: 'میلی‌لیتر (milliliter)',
        'cubic-meter': 'متر مکعب (cubic meter)',
        gallon: 'گالن (gallon)',
        quart: 'کوارت (quart)',
        pint: 'پاینت (pint)',
        cup: 'فنجان (cup)',
    }
};

export const allUnits = Object.values(unitCategories).flat();

export const plateLetters = [
  'الف', 'ب', 'پ', 'ت', 'ث', 'ج', 'چ', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'ژ', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ک', 'گ', 'ل', 'م', 'ن', 'و', 'ه', 'ی'
];

export const plateCodes: { [key: number]: { province: string; cities: { [letter: string]: string } } } = {
    11: { province: "تهران", cities: { "الف": "تهران مرکزی", "ب": "شمال تهران", "ج": "جنوب تهران", "د": "شرق تهران", "ه": "غرب تهران" } },
    12: { province: "تهران", cities: { "الف": "شهریار", "ب": "ملارد", "ج": "رباط‌کریم" } },
    13: { province: "اصفهان", cities: { "الف": "اصفهان", "ب": "شهرضا", "ج": "کاشان", "د": "خمینی‌شهر", "ه": "نجف‌آباد", "و": "فولادشهر" } },
    14: { province: "یزد", cities: { "الف": "یزد", "ب": "میبد", "ج": "اردکان" } },
    15: { province: "هرمزگان", cities: { "الف": "بندرعباس", "ب": "قشم", "ج": "کیش", "د": "بندر لنگه" } },
    16: { province: "فارس", cities: { "الف": "کازرون", "ب": "لامرد" } },
    17: { province: "فارس", cities: { "الف": "شیراز", "ب": "مرودشت", "ج": "جهرم", "د": "فسا", "ه": "داراب" } },
    18: { province: "فارس", cities: { "الف": "لار", "ب": "اقلید" } },
    19: { province: "فارس", cities: { "الف": "آباده", "ب": "ارسنجان" } },
    21: { province: "آذربایجان شرقی", cities: { "الف": "تبریز", "ب": "مراغه", "ج": "آذرشهر" } },
    22: { province: "آذربایجان شرقی", cities: { "الف": "سراب", "ب": "مرند" } },
    23: { province: "آذربایجان شرقی", cities: { "الف": "اهر", "ب": "میانه" } },
    24: { province: "آذربایجان شرقی", cities: { "الف": "بناب", "ب": "شبستر" } },
    25: { province: "آذربایجان غربی", cities: { "الف": "ارومیه", "ب": "خوی", "ج": "سلماس", "د": "مهاباد" } },
    26: { province: "آذربایجان غربی", cities: { "الف": "میاندوآب", "ب": "بوکان" } },
    27: { province: "اردبیل", cities: { "الف": "اردبیل", "ب": "مشگین‌شهر", "ج": "پارس‌آباد" } },
    28: { province: "اردبیل", cities: { "الف": "خلخال", "ب": "گرمی" } },
    29: { province: "البرز", cities: { "الف": "کرج", "ب": "نظرآباد", "ج": "فردیس", "د": "ماهدشت" } },
    31: { province: "ایلام", cities: { "الف": "ایلام", "ب": "دهلران", "ج": "آبدانان" } },
    32: { province: "ایلام", cities: { "الف": "مهران", "ب": "دره‌شهر" } },
    33: { province: "بوشهر", cities: { "الف": "بوشهر", "ب": "برازجان", "ج": "گناوه" } },
    34: { province: "چهارمحال و بختیاری", cities: { "الف": "شهرکرد", "ب": "فارسان", "ج": "بروجن" } },
    35: { province: "چهارمحال و بختیاری", cities: { "الف": "لردگان", "ب": "کیار" } },
    36: { province: "خراسان جنوبی", cities: { "الف": "بیرجند", "ب": "قائن", "ج": "فردوس" } },
    37: { province: "خراسان جنوبی", cities: { "الف": "طبس", "ب": "نهبندان" } },
    38: { province: "خراسان شمالی", cities: { "الف": "بجنورد", "ب": "شیروان", "ج": "اسفراین" } },
    39: { province: "خراسان شمالی", cities: { "الف": "فاروج", "ب": "جاجرم" } },
    41: { province: "خراسان رضوی", cities: { "الف": "تربت‌حیدریه", "ب": "کاشمر" } },
    42: { province: "خراسان رضوی", cities: { "الف": "تربت‌جام", "ب": "تایباد" } },
    43: { province: "خراسان رضوی", cities: { "الف": "قوچان", "ب": "درگز" } },
    44: { province: "خراسان رضوی", cities: { "الف": "گناباد", "ب": "خواف" } },
    45: { province: "خراسان رضوی", cities: { "الف": "مشهد", "ب": "سبزوار", "ج": "نیشابور", "د": "چناران", "ه": "بردسکن" } },
    46: { province: "خوزستان", cities: { "الف": "اهواز", "ب": "آبادان", "ج": "خرمشهر", "د": "مسجدسلیمان", "ه": "دزفول" } },
    47: { province: "خوزستان", cities: { "الف": "اندیمشک", "ب": "شوشتر" } },
    48: { province: "خوزستان", cities: { "الف": "بهبهان", "ب": "رامهرمز" } },
    49: { province: "خوزستان", cities: { "الف": "ایذه", "ب": "گتوند" } },
    51: { province: "زنجان", cities: { "الف": "زنجان", "ب": "خرمدره", "ج": "ابهر" } },
    52: { province: "زنجان", cities: { "الف": "قیدار", "ب": "خدابنده" } },
    53: { province: "سمنان", cities: { "الف": "سمنان", "ب": "شاهرود", "ج": "دامغان" } },
    54: { province: "سمنان", cities: { "الف": "گرمسار", "ب": "آرادان" } },
    55: { province: "سیستان و بلوچستان", cities: { "الف": "زاهدان", "ب": "چابهار", "ج": "ایرانشهر" } },
    56: { province: "سیستان و بلوچستان", cities: { "الف": "زابل", "ب": "سراوان" } },
    57: { province: "کرمان", cities: { "الف": "کرمان", "ب": "رفسنجان", "ج": "سیرجان", "د": "جیرفت" } },
    58: { province: "کرمان", cities: { "الف": "بم", "ب": "کهنوج" } },
    59: { province: "کرمان", cities: { "الف": "زرند", "ب": "بردسیر" } },
    61: { province: "کرمانشاه", cities: { "الف": "کرمانشاه", "ب": "اسلام‌آباد غرب", "ج": "پاوه" } },
    62: { province: "کرمانشاه", cities: { "الف": "سنقر", "ب": "صحنه" } },
    63: { province: "کرمانشاه", cities: { "الف": "کنگاور", "ب": "هرسین" } },
    64: { province: "کهگیلویه و بویراحمد", cities: { "الف": "یاسوج", "ب": "دوگنبدان" } },
    65: { province: "کهگیلویه و بویراحمد", cities: { "الف": "گچساران", "ب": "دهدشت" } },
    66: { province: "گلستان", cities: { "الف": "گرگان", "ب": "گنبدکاووس", "ج": "علی‌آباد" } },
    67: { province: "تهران", cities: { "الف": "ورامین", "ب": "ری", "ج": "پاکدشت", "د": "دماوند" } },
    68: { province: "گیلان", cities: { "الف": "رشت", "ب": "بندر انزلی", "ج": "لاهیجان", "د": "آستارا" } },
    69: { province: "گیلان", cities: { "الف": "رودسر", "ب": "فومن" } },
    71: { province: "لرستان", cities: { "الف": "خرم‌آباد", "ب": "بروجرد", "ج": "دورود" } },
    72: { province: "لرستان", cities: { "الف": "الیگودرز", "ب": "کوهدشت" } },
    73: { province: "مازندران", cities: { "الف": "ساری", "ب": "بابل", "ج": "آمل", "د": "بابلسر" } },
    74: { province: "مازندران", cities: { "الف": "گرگان", "ب": "نوشهر" } }, // Note: Gorgan is in Golestan
    75: { province: "مازندران", cities: { "الف": "چالوس", "ب": "تنکابن" } },
    76: { province: "مرکزی", cities: { "الف": "اراک", "ب": "ساوه", "ج": "خمین" } },
    77: { province: "مرکزی", cities: { "الف": "محلات", "ب": "دلیجان" } },
    78: { province: "هرمزگان", cities: { "الف": "میناب", "ب": "رودان" } },
    79: { province: "هرمزگان", cities: { "الف": "حاجی‌آباد", "ب": "پارسیان" } },
    81: { province: "همدان", cities: { "الف": "همدان", "ب": "ملایر", "ج": "نهاوند" } },
    82: { province: "همدان", cities: { "الف": "تویسرکان", "ب": "اسدآباد" } },
    83: { province: "یزد", cities: { "الف": "مهریز", "ب": "بافق" } },
    84: { province: "یزد", cities: { "الف": "ابرکوه", "ب": "تفت" } },
    85: { province: "قزوین", cities: { "الف": "قزوین", "ب": "تاکستان", "ج": "آبیک" } },
    86: { province: "قم", cities: { "الف": "قم" } },
    87: { province: "کردستان", cities: { "الف": "سنندج", "ب": "مریوان", "ج": "بانه" } },
    88: { province: "کردستان", cities: { "الف": "سقز", "ب": "قروه" } },
    89: { province: "کردستان", cities: { "الف": "بیجار", "ب": "دیواندره" } },
    91: { province: "اصفهان", cities: { "الف": "خوانسار", "ب": "گلپایگان" } },
    92: { province: "اصفهان", cities: { "الف": "فریدن", "ب": "چادگان" } },
    93: { province: "اصفهان", cities: { "الف": "فریدونشهر", "ب": "سمیرم" } },
    94: { province: "اصفهان", cities: { "الف": "نطنز", "ب": "آران و بیدگل" } },
    95: { province: "اصفهان", cities: { "الف": "لنجان", "ب": "مبارکه" } },
    96: { province: "اصفهان", cities: { "الف": "دهاقان", "ب": "تیران و کرون" } },
    97: { province: "اصفهان", cities: { "الف": "اردستان", "ب": "نائین" } },
    98: { province: "اصفهان", cities: { "الف": "فلاورجان", "ب": "برخوار" } },
    444: { province: "کل کشور", cities: { "ع": "نیروهای مسلح" } },
    555: { province: "کل کشور", cities: { "ص": "سفارت و کنسولگری" } },
    666: { province: "کل کشور", cities: { "پ": "پلیس" } },
    777: { province: "کل کشور", cities: { "ت": "تاکسی" } },
    888: { province: "کل کشور", cities: { "ث": "ثبت موقت" } },
    999: { province: "کل کشور", cities: { "د": "دولتی" } }
};
